// GENERATED by scripts/generate-wire-fields.mjs from resources/ast-schema.json.
// Do not edit: run `node scripts/generate-wire-fields.mjs` instead.
//
// PART 12 section 11 - a property the schema does not name is refused on
// ingest - needs the named set at runtime, and the schema is not shipped
// with the package.

/** Properties the schema names for each node type. */
export const WIRE_FIELDS: Readonly<Record<string, readonly string[]>> = {
  "abbreviation": ["abbr", "attrs", "expansion", "pos", "type"],
  "abbreviation_def": ["abbr", "attrs", "expansion", "pos", "type"],
  "admonition": ["attrs", "children", "kind", "label", "pos", "title", "type"],
  "autolink": ["attrs", "href", "pos", "text", "type"],
  "block_quote": ["attrs", "children", "pos", "type"],
  "caption_number": ["attrs", "n", "pos", "type"],
  "citation_group": ["attrs", "items", "mode", "pos", "raw", "type"],
  "code": ["attrs", "pos", "type", "value"],
  "code_block": ["attrs", "content", "header", "label", "lang", "pos", "type"],
  "comment": ["attrs", "block", "content", "pos", "type"],
  "critic_comment": ["attrs", "pos", "text", "type"],
  "definition_description": ["attrs", "children", "pos", "type"],
  "definition_list": ["attrs", "items", "pos", "type"],
  "definition_term": ["attrs", "children", "pos", "type"],
  "delete": ["attrs", "children", "pos", "type"],
  "div": ["attrs", "children", "label", "pos", "type"],
  "document": ["children", "srcByteLength", "type"],
  "emphasis": ["attrs", "children", "pos", "type"],
  "escaped_text": ["attrs", "pos", "type", "value"],
  "figure": ["attrs", "caption", "pos", "shortCaption", "target", "type"],
  "footnote": ["attrs", "children", "label", "pos", "type"],
  "footnote_ref": ["attrs", "id", "number", "pos", "type"],
  "frontmatter": ["content", "format", "pos", "type"],
  "hard_break": ["attrs", "pos", "type"],
  "heading": ["attrs", "children", "level", "pos", "type"],
  "heading_ref": ["attrs", "href", "pos", "target", "type"],
  "highlight": ["attrs", "children", "pos", "type"],
  "image": ["alt", "attrs", "pos", "rawRef", "ref", "src", "title", "type"],
  "inline_extension": ["attrs", "content", "name", "pos", "type"],
  "inline_footnote": ["attrs", "inline", "number", "pos", "type"],
  "insert": ["attrs", "children", "pos", "type"],
  "line_block": ["attrs", "children", "pos", "type"],
  "link": ["attrs", "children", "href", "pos", "rawRef", "ref", "title", "type"],
  "link_reference_definition": ["attrs", "href", "label", "pos", "title", "type"],
  "list": ["attrs", "bareMarker", "bulletChar", "delim", "items", "olType", "ordered", "pos", "start", "tight", "type"],
  "list_item": ["attrs", "checked", "children", "pos", "type"],
  "literal_inline": ["attrs", "content", "pos", "type"],
  "math": ["attrs", "content", "display", "pos", "type"],
  "mention": ["attrs", "pos", "type", "user"],
  "paragraph": ["attrs", "children", "pos", "type"],
  "raw_block": ["attrs", "content", "format", "pos", "type"],
  "raw_inline": ["attrs", "content", "format", "pos", "type"],
  "smart_punctuation": ["attrs", "glyph", "kind", "pos", "type", "value"],
  "soft_break": ["attrs", "pos", "type"],
  "span": ["attrs", "children", "pos", "type"],
  "strike": ["attrs", "children", "pos", "type"],
  "strong": ["attrs", "boldItalic", "children", "pos", "type"],
  "subscript": ["attrs", "children", "pos", "type"],
  "substitution": ["attrs", "newText", "oldText", "pos", "type"],
  "superscript": ["attrs", "children", "pos", "type"],
  "symbol": ["attrs", "name", "pos", "type"],
  "table": ["attrs", "caption", "pos", "rows", "shortCaption", "type"],
  "table_cell": ["align", "attrs", "children", "header", "pos", "span", "type"],
  "table_row": ["attrs", "cells", "pos", "type"],
  "tag": ["attrs", "name", "pos", "type"],
  "text": ["attrs", "pos", "type", "value"],
  "thematic_break": ["attrs", "marker", "pos", "type"],
  "underline": ["attrs", "children", "pos", "type"],
}

/** Properties the schema names for the objects that hang off a node. */
export const WIRE_HELPER_FIELDS: Readonly<Record<string, readonly string[]>> = {
  "attrs": ["classes", "id", "keyValues", "order"],
  "pos": ["endColumn", "endLine", "endOffset", "startColumn", "startLine", "startOffset"],
}

/**
 * Field names that hold NODES, so section 12(c)'s unknown-type check knows
 * where a node can be. A union across types: `content` holds nodes on
 * `inline_extension` and a string on `code_block`, and descending a name into
 * a string finds nothing, so the union is safe in both directions.
 *
 * `keyValues` is absent, and that is the point: its values are strings, and an
 * attribute may legally be named `type`, so `{type=widget}` puts an object
 * shaped {"type":"widget"} in the tree.
 */
export const NODE_FIELDS: readonly string[] = [
  "caption",
  "cells",
  "children",
  "content",
  "inline",
  "items",
  "locator",
  "prefix",
  "rows",
  "shortCaption",
  "suffix",
  "target",
  "title",
]

/**
 * What the schema puts at each node position, keyed `<owning type>.<field>`,
 * so section 12(c)'s string-`type` requirement lands where a NODE belongs and
 * nowhere else.
 *
 * - `"nodes"` - an array of nodes; each ELEMENT carries a string `type`. About
 *   the elements, not the container: a non-array sitting where the array
 *   belongs is the unruled wrong-TYPE class, not this clause's business.
 * - `"node"` - a single node, e.g. `figure.target`; the object itself carries
 *   one.
 * - `"records"` - an array of plain records the schema gives no `type` at all.
 *   Only `citation_group.items` today: a citation item is
 *   `{key, suppressAuthor, prefix?, locator?, suffix?}`.
 *
 * The owning type is part of the key because one field name means different
 * things in different places: `items` holds nodes on `list` and plain records
 * on `citation_group`.
 */
export const NODE_POSITION_KIND: Readonly<Record<string, 'nodes' | 'node' | 'records'>> = {
  "admonition.children": "nodes",
  "admonition.title": "nodes",
  "block_quote.children": "nodes",
  "citation_group.items": "records",
  "definition_description.children": "nodes",
  "definition_list.items": "nodes",
  "definition_term.children": "nodes",
  "delete.children": "nodes",
  "div.children": "nodes",
  "document.children": "nodes",
  "emphasis.children": "nodes",
  "figure.caption": "nodes",
  "figure.shortCaption": "nodes",
  "figure.target": "node",
  "footnote.children": "nodes",
  "heading.children": "nodes",
  "highlight.children": "nodes",
  "inline_extension.content": "nodes",
  "inline_footnote.inline": "nodes",
  "insert.children": "nodes",
  "line_block.children": "nodes",
  "link.children": "nodes",
  "list.items": "nodes",
  "list_item.children": "nodes",
  "paragraph.children": "nodes",
  "span.children": "nodes",
  "strike.children": "nodes",
  "strong.children": "nodes",
  "subscript.children": "nodes",
  "superscript.children": "nodes",
  "table.caption": "nodes",
  "table.rows": "nodes",
  "table.shortCaption": "nodes",
  "table_cell.children": "nodes",
  "table_row.cells": "nodes",
  "underline.children": "nodes",
}

/**
 * What the schema REQUIRES of each type, and of the two typeless objects that
 * hang off a node (PART 12 section 12(d)).
 *
 * (d) validates the WHOLE payload against the schema at DECODE - types and
 * required fields together - refused with the same typed error (a), (b) and
 * (c) already require. Not a fourth list of leniency points: the schema is the
 * list, and the rows that diverged across engines were only ever divergent
 * because nothing consulted it.
 */
export const WIRE_REQUIRED: Readonly<Record<string, readonly string[]>> = {
  "abbreviation": ["abbr", "expansion", "type"],
  "abbreviation_def": ["abbr", "expansion", "type"],
  "admonition": ["children", "kind", "type"],
  "attrs": [],
  "autolink": ["href", "type"],
  "block_quote": ["children", "type"],
  "caption_number": ["type"],
  "citation_group": ["items", "raw", "type"],
  "code": ["type", "value"],
  "code_block": ["content", "type"],
  "comment": ["block", "content", "type"],
  "critic_comment": ["text", "type"],
  "definition_description": ["children", "type"],
  "definition_list": ["items", "type"],
  "definition_term": ["children", "type"],
  "delete": ["children", "type"],
  "div": ["children", "type"],
  "document": ["children", "srcByteLength", "type"],
  "emphasis": ["children", "type"],
  "escaped_text": ["type", "value"],
  "figure": ["caption", "target", "type"],
  "footnote": ["children", "label", "type"],
  "footnote_ref": ["type"],
  "frontmatter": ["content", "format", "type"],
  "hard_break": ["type"],
  "heading": ["children", "level", "type"],
  "heading_ref": ["target", "type"],
  "highlight": ["children", "type"],
  "image": ["alt", "src", "type"],
  "inline_extension": ["content", "name", "type"],
  "inline_footnote": ["inline", "type"],
  "insert": ["children", "type"],
  "line_block": ["children", "type"],
  "link": ["children", "href", "type"],
  "link_reference_definition": ["href", "label", "type"],
  "list": ["items", "ordered", "tight", "type"],
  "list_item": ["children", "type"],
  "literal_inline": ["content", "type"],
  "math": ["content", "display", "type"],
  "mention": ["type", "user"],
  "paragraph": ["children", "type"],
  "pos": ["endColumn", "endLine", "endOffset", "startColumn", "startLine", "startOffset"],
  "raw_block": ["content", "format", "type"],
  "raw_inline": ["content", "format", "type"],
  "smart_punctuation": ["kind", "type", "value"],
  "soft_break": ["type"],
  "span": ["children", "type"],
  "strike": ["children", "type"],
  "strong": ["children", "type"],
  "subscript": ["children", "type"],
  "substitution": ["newText", "oldText", "type"],
  "superscript": ["children", "type"],
  "symbol": ["name", "type"],
  "table": ["rows", "type"],
  "table_cell": ["children", "header", "type"],
  "table_row": ["cells", "type"],
  "tag": ["name", "type"],
  "text": ["type", "value"],
  "thematic_break": ["type"],
  "underline": ["children", "type"],
}

/**
 * The VALUE SHAPE the schema gives each property, keyed by owning type.
 *
 * The kinds are the subset of JSON Schema the schema actually uses, so the
 * walk answers (d) without re-implementing a validator: `string`, `boolean`,
 * `integer` with an optional minimum, `enum:` with NUL-separated members,
 * `string[]`, `array`, `object`, and `node` for a single nested node.
 *
 * `type` is absent on purpose - section 12(c) settles it and carries its own
 * error, and two producers of one rule is the hazard rather than the gap.
 */
export const WIRE_VALUE_KINDS: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  "abbreviation": { "abbr": "string", "attrs": "object", "expansion": "string", "pos": "object" },
  "abbreviation_def": { "abbr": "string", "attrs": "object", "expansion": "string", "pos": "object" },
  "admonition": { "attrs": "object", "children": "array", "kind": "string", "label": "string", "pos": "object", "title": "array" },
  "attrs": { "classes": "string[]", "id": "string", "keyValues": "object", "order": "string[]" },
  "autolink": { "attrs": "object", "href": "string", "pos": "object", "text": "string" },
  "block_quote": { "attrs": "object", "children": "array", "pos": "object" },
  "caption_number": { "attrs": "object", "n": "integer", "pos": "object" },
  "citation_group": { "attrs": "object", "items": "array", "pos": "object", "raw": "string" },
  "code": { "attrs": "object", "pos": "object", "value": "string" },
  "code_block": { "attrs": "object", "content": "string", "header": "string", "label": "string", "lang": "string", "pos": "object" },
  "comment": { "attrs": "object", "block": "boolean", "content": "string", "pos": "object" },
  "critic_comment": { "attrs": "object", "pos": "object", "text": "string" },
  "definition_description": { "attrs": "object", "children": "array", "pos": "object" },
  "definition_list": { "attrs": "object", "items": "array", "pos": "object" },
  "definition_term": { "attrs": "object", "children": "array", "pos": "object" },
  "delete": { "attrs": "object", "children": "array", "pos": "object" },
  "div": { "attrs": "object", "children": "array", "label": "string", "pos": "object" },
  "document": { "children": "array", "srcByteLength": "integer>=0" },
  "emphasis": { "attrs": "object", "children": "array", "pos": "object" },
  "escaped_text": { "attrs": "object", "pos": "object", "value": "string" },
  "figure": { "attrs": "object", "caption": "array", "pos": "object", "shortCaption": "array" },
  "footnote": { "attrs": "object", "children": "array", "label": "string", "pos": "object" },
  "footnote_ref": { "attrs": "object", "id": "string", "number": "integer", "pos": "object" },
  "frontmatter": { "content": "string", "format": "string", "pos": "object" },
  "hard_break": { "attrs": "object", "pos": "object" },
  "heading": { "attrs": "object", "children": "array", "level": "integer>=1", "pos": "object" },
  "heading_ref": { "attrs": "object", "href": "string", "pos": "object", "target": "string" },
  "highlight": { "attrs": "object", "children": "array", "pos": "object" },
  "image": { "alt": "string", "attrs": "object", "pos": "object", "rawRef": "string", "ref": "string", "src": "string", "title": "string" },
  "inline_extension": { "attrs": "object", "content": "array", "name": "string", "pos": "object" },
  "inline_footnote": { "attrs": "object", "inline": "array", "number": "integer", "pos": "object" },
  "insert": { "attrs": "object", "children": "array", "pos": "object" },
  "line_block": { "attrs": "object", "children": "array", "pos": "object" },
  "link": { "attrs": "object", "children": "array", "href": "string", "pos": "object", "rawRef": "string", "ref": "string", "title": "string" },
  "link_reference_definition": { "attrs": "object", "href": "string", "label": "string", "pos": "object", "title": "string" },
  "list": { "attrs": "object", "bulletChar": "enum:-\u0000*", "delim": "enum:.\u0000)", "items": "array", "olType": "enum:a\u0000A\u0000i\u0000I", "ordered": "boolean", "pos": "object", "start": "integer", "tight": "boolean" },
  "list_item": { "attrs": "object", "checked": "boolean", "children": "array", "pos": "object" },
  "literal_inline": { "attrs": "object", "content": "string", "pos": "object" },
  "math": { "attrs": "object", "content": "string", "display": "boolean", "pos": "object" },
  "mention": { "attrs": "object", "pos": "object", "user": "string" },
  "paragraph": { "attrs": "object", "children": "array", "pos": "object" },
  "pos": { "endColumn": "integer>=1", "endLine": "integer>=1", "endOffset": "integer>=0", "startColumn": "integer>=1", "startLine": "integer>=1", "startOffset": "integer>=0" },
  "raw_block": { "attrs": "object", "content": "string", "format": "string", "pos": "object" },
  "raw_inline": { "attrs": "object", "content": "string", "format": "string", "pos": "object" },
  "smart_punctuation": { "attrs": "object", "glyph": "string", "kind": "string", "pos": "object", "value": "string" },
  "soft_break": { "attrs": "object", "pos": "object" },
  "span": { "attrs": "object", "children": "array", "pos": "object" },
  "strike": { "attrs": "object", "children": "array", "pos": "object" },
  "strong": { "attrs": "object", "children": "array", "pos": "object" },
  "subscript": { "attrs": "object", "children": "array", "pos": "object" },
  "substitution": { "attrs": "object", "newText": "string", "oldText": "string", "pos": "object" },
  "superscript": { "attrs": "object", "children": "array", "pos": "object" },
  "symbol": { "attrs": "object", "name": "string", "pos": "object" },
  "table": { "attrs": "object", "caption": "array", "pos": "object", "rows": "array", "shortCaption": "array" },
  "table_cell": { "align": "enum:left\u0000right\u0000center", "attrs": "object", "children": "array", "header": "boolean", "pos": "object", "span": "enum:rowspan\u0000colspan" },
  "table_row": { "attrs": "object", "cells": "array", "pos": "object" },
  "tag": { "attrs": "object", "name": "string", "pos": "object" },
  "text": { "attrs": "object", "pos": "object", "value": "string" },
  "thematic_break": { "attrs": "object", "marker": "enum:-\u0000*\u0000_", "pos": "object" },
  "underline": { "attrs": "object", "children": "array", "pos": "object" },
}

/**
 * Which node TYPES each position admits, keyed `<owning type>.<field>`.
 *
 * `NODE_POSITION_KIND` says a position holds nodes; this says which. Without
 * it the schema is half-consulted: a `paragraph` in another paragraph's
 * `children` is a block where the schema names `inlineNode`, and it decoded
 * cleanly and then threw an untyped error from inside the renderer.
 *
 * Positions whose kind is `records` are absent on purpose - those hold plain
 * records with no `type`, and requiring one would refuse a tree this engine's
 * own parser produced (section 9(a)).
 */
export const NODE_POSITION_TYPES: Readonly<Record<string, readonly string[]>> = {
  "admonition.children": ["abbreviation_def", "admonition", "block_quote", "code_block", "comment", "definition_description", "definition_list", "definition_term", "div", "figure", "footnote", "frontmatter", "heading", "image", "line_block", "link_reference_definition", "list", "list_item", "paragraph", "raw_block", "table", "table_cell", "table_row", "thematic_break"],
  "admonition.title": ["abbreviation", "autolink", "caption_number", "citation_group", "code", "comment", "critic_comment", "delete", "emphasis", "escaped_text", "footnote_ref", "hard_break", "heading_ref", "highlight", "image", "inline_extension", "inline_footnote", "insert", "link", "literal_inline", "math", "mention", "raw_inline", "smart_punctuation", "soft_break", "span", "strike", "strong", "subscript", "substitution", "superscript", "symbol", "tag", "text", "underline"],
  "block_quote.children": ["abbreviation_def", "admonition", "block_quote", "code_block", "comment", "definition_description", "definition_list", "definition_term", "div", "figure", "footnote", "frontmatter", "heading", "image", "line_block", "link_reference_definition", "list", "list_item", "paragraph", "raw_block", "table", "table_cell", "table_row", "thematic_break"],
  "definition_description.children": ["abbreviation_def", "admonition", "block_quote", "code_block", "comment", "definition_description", "definition_list", "definition_term", "div", "figure", "footnote", "frontmatter", "heading", "image", "line_block", "link_reference_definition", "list", "list_item", "paragraph", "raw_block", "table", "table_cell", "table_row", "thematic_break"],
  "definition_list.items": ["definition_description", "definition_term"],
  "definition_term.children": ["abbreviation", "autolink", "caption_number", "citation_group", "code", "comment", "critic_comment", "delete", "emphasis", "escaped_text", "footnote_ref", "hard_break", "heading_ref", "highlight", "image", "inline_extension", "inline_footnote", "insert", "link", "literal_inline", "math", "mention", "raw_inline", "smart_punctuation", "soft_break", "span", "strike", "strong", "subscript", "substitution", "superscript", "symbol", "tag", "text", "underline"],
  "delete.children": ["abbreviation", "autolink", "caption_number", "citation_group", "code", "comment", "critic_comment", "delete", "emphasis", "escaped_text", "footnote_ref", "hard_break", "heading_ref", "highlight", "image", "inline_extension", "inline_footnote", "insert", "link", "literal_inline", "math", "mention", "raw_inline", "smart_punctuation", "soft_break", "span", "strike", "strong", "subscript", "substitution", "superscript", "symbol", "tag", "text", "underline"],
  "div.children": ["abbreviation_def", "admonition", "block_quote", "code_block", "comment", "definition_description", "definition_list", "definition_term", "div", "figure", "footnote", "frontmatter", "heading", "image", "line_block", "link_reference_definition", "list", "list_item", "paragraph", "raw_block", "table", "table_cell", "table_row", "thematic_break"],
  "document.children": ["abbreviation_def", "admonition", "block_quote", "code_block", "comment", "definition_description", "definition_list", "definition_term", "div", "figure", "footnote", "frontmatter", "heading", "image", "line_block", "link_reference_definition", "list", "list_item", "paragraph", "raw_block", "table", "table_cell", "table_row", "thematic_break"],
  "emphasis.children": ["abbreviation", "autolink", "caption_number", "citation_group", "code", "comment", "critic_comment", "delete", "emphasis", "escaped_text", "footnote_ref", "hard_break", "heading_ref", "highlight", "image", "inline_extension", "inline_footnote", "insert", "link", "literal_inline", "math", "mention", "raw_inline", "smart_punctuation", "soft_break", "span", "strike", "strong", "subscript", "substitution", "superscript", "symbol", "tag", "text", "underline"],
  "figure.caption": ["abbreviation", "autolink", "caption_number", "citation_group", "code", "comment", "critic_comment", "delete", "emphasis", "escaped_text", "footnote_ref", "hard_break", "heading_ref", "highlight", "image", "inline_extension", "inline_footnote", "insert", "link", "literal_inline", "math", "mention", "raw_inline", "smart_punctuation", "soft_break", "span", "strike", "strong", "subscript", "substitution", "superscript", "symbol", "tag", "text", "underline"],
  "figure.shortCaption": ["abbreviation", "autolink", "caption_number", "citation_group", "code", "comment", "critic_comment", "delete", "emphasis", "escaped_text", "footnote_ref", "hard_break", "heading_ref", "highlight", "image", "inline_extension", "inline_footnote", "insert", "link", "literal_inline", "math", "mention", "raw_inline", "smart_punctuation", "soft_break", "span", "strike", "strong", "subscript", "substitution", "superscript", "symbol", "tag", "text", "underline"],
  "figure.target": ["block_quote", "code_block", "image", "paragraph", "table"],
  "footnote.children": ["abbreviation_def", "admonition", "block_quote", "code_block", "comment", "definition_description", "definition_list", "definition_term", "div", "figure", "footnote", "frontmatter", "heading", "image", "line_block", "link_reference_definition", "list", "list_item", "paragraph", "raw_block", "table", "table_cell", "table_row", "thematic_break"],
  "heading.children": ["abbreviation", "autolink", "caption_number", "citation_group", "code", "comment", "critic_comment", "delete", "emphasis", "escaped_text", "footnote_ref", "hard_break", "heading_ref", "highlight", "image", "inline_extension", "inline_footnote", "insert", "link", "literal_inline", "math", "mention", "raw_inline", "smart_punctuation", "soft_break", "span", "strike", "strong", "subscript", "substitution", "superscript", "symbol", "tag", "text", "underline"],
  "highlight.children": ["abbreviation", "autolink", "caption_number", "citation_group", "code", "comment", "critic_comment", "delete", "emphasis", "escaped_text", "footnote_ref", "hard_break", "heading_ref", "highlight", "image", "inline_extension", "inline_footnote", "insert", "link", "literal_inline", "math", "mention", "raw_inline", "smart_punctuation", "soft_break", "span", "strike", "strong", "subscript", "substitution", "superscript", "symbol", "tag", "text", "underline"],
  "inline_extension.content": ["abbreviation", "autolink", "caption_number", "citation_group", "code", "comment", "critic_comment", "delete", "emphasis", "escaped_text", "footnote_ref", "hard_break", "heading_ref", "highlight", "image", "inline_extension", "inline_footnote", "insert", "link", "literal_inline", "math", "mention", "raw_inline", "smart_punctuation", "soft_break", "span", "strike", "strong", "subscript", "substitution", "superscript", "symbol", "tag", "text", "underline"],
  "inline_footnote.inline": ["abbreviation", "autolink", "caption_number", "citation_group", "code", "comment", "critic_comment", "delete", "emphasis", "escaped_text", "footnote_ref", "hard_break", "heading_ref", "highlight", "image", "inline_extension", "inline_footnote", "insert", "link", "literal_inline", "math", "mention", "raw_inline", "smart_punctuation", "soft_break", "span", "strike", "strong", "subscript", "substitution", "superscript", "symbol", "tag", "text", "underline"],
  "insert.children": ["abbreviation", "autolink", "caption_number", "citation_group", "code", "comment", "critic_comment", "delete", "emphasis", "escaped_text", "footnote_ref", "hard_break", "heading_ref", "highlight", "image", "inline_extension", "inline_footnote", "insert", "link", "literal_inline", "math", "mention", "raw_inline", "smart_punctuation", "soft_break", "span", "strike", "strong", "subscript", "substitution", "superscript", "symbol", "tag", "text", "underline"],
  "line_block.children": ["abbreviation_def", "admonition", "block_quote", "code_block", "comment", "definition_description", "definition_list", "definition_term", "div", "figure", "footnote", "frontmatter", "heading", "image", "line_block", "link_reference_definition", "list", "list_item", "paragraph", "raw_block", "table", "table_cell", "table_row", "thematic_break"],
  "link.children": ["abbreviation", "autolink", "caption_number", "citation_group", "code", "comment", "critic_comment", "delete", "emphasis", "escaped_text", "footnote_ref", "hard_break", "heading_ref", "highlight", "image", "inline_extension", "inline_footnote", "insert", "link", "literal_inline", "math", "mention", "raw_inline", "smart_punctuation", "soft_break", "span", "strike", "strong", "subscript", "substitution", "superscript", "symbol", "tag", "text", "underline"],
  "list.items": ["list_item"],
  "list_item.children": ["abbreviation_def", "admonition", "block_quote", "code_block", "comment", "definition_description", "definition_list", "definition_term", "div", "figure", "footnote", "frontmatter", "heading", "image", "line_block", "link_reference_definition", "list", "list_item", "paragraph", "raw_block", "table", "table_cell", "table_row", "thematic_break"],
  "paragraph.children": ["abbreviation", "autolink", "caption_number", "citation_group", "code", "comment", "critic_comment", "delete", "emphasis", "escaped_text", "footnote_ref", "hard_break", "heading_ref", "highlight", "image", "inline_extension", "inline_footnote", "insert", "link", "literal_inline", "math", "mention", "raw_inline", "smart_punctuation", "soft_break", "span", "strike", "strong", "subscript", "substitution", "superscript", "symbol", "tag", "text", "underline"],
  "span.children": ["abbreviation", "autolink", "caption_number", "citation_group", "code", "comment", "critic_comment", "delete", "emphasis", "escaped_text", "footnote_ref", "hard_break", "heading_ref", "highlight", "image", "inline_extension", "inline_footnote", "insert", "link", "literal_inline", "math", "mention", "raw_inline", "smart_punctuation", "soft_break", "span", "strike", "strong", "subscript", "substitution", "superscript", "symbol", "tag", "text", "underline"],
  "strike.children": ["abbreviation", "autolink", "caption_number", "citation_group", "code", "comment", "critic_comment", "delete", "emphasis", "escaped_text", "footnote_ref", "hard_break", "heading_ref", "highlight", "image", "inline_extension", "inline_footnote", "insert", "link", "literal_inline", "math", "mention", "raw_inline", "smart_punctuation", "soft_break", "span", "strike", "strong", "subscript", "substitution", "superscript", "symbol", "tag", "text", "underline"],
  "strong.children": ["abbreviation", "autolink", "caption_number", "citation_group", "code", "comment", "critic_comment", "delete", "emphasis", "escaped_text", "footnote_ref", "hard_break", "heading_ref", "highlight", "image", "inline_extension", "inline_footnote", "insert", "link", "literal_inline", "math", "mention", "raw_inline", "smart_punctuation", "soft_break", "span", "strike", "strong", "subscript", "substitution", "superscript", "symbol", "tag", "text", "underline"],
  "subscript.children": ["abbreviation", "autolink", "caption_number", "citation_group", "code", "comment", "critic_comment", "delete", "emphasis", "escaped_text", "footnote_ref", "hard_break", "heading_ref", "highlight", "image", "inline_extension", "inline_footnote", "insert", "link", "literal_inline", "math", "mention", "raw_inline", "smart_punctuation", "soft_break", "span", "strike", "strong", "subscript", "substitution", "superscript", "symbol", "tag", "text", "underline"],
  "superscript.children": ["abbreviation", "autolink", "caption_number", "citation_group", "code", "comment", "critic_comment", "delete", "emphasis", "escaped_text", "footnote_ref", "hard_break", "heading_ref", "highlight", "image", "inline_extension", "inline_footnote", "insert", "link", "literal_inline", "math", "mention", "raw_inline", "smart_punctuation", "soft_break", "span", "strike", "strong", "subscript", "substitution", "superscript", "symbol", "tag", "text", "underline"],
  "table.caption": ["abbreviation", "autolink", "caption_number", "citation_group", "code", "comment", "critic_comment", "delete", "emphasis", "escaped_text", "footnote_ref", "hard_break", "heading_ref", "highlight", "image", "inline_extension", "inline_footnote", "insert", "link", "literal_inline", "math", "mention", "raw_inline", "smart_punctuation", "soft_break", "span", "strike", "strong", "subscript", "substitution", "superscript", "symbol", "tag", "text", "underline"],
  "table.rows": ["table_row"],
  "table.shortCaption": ["abbreviation", "autolink", "caption_number", "citation_group", "code", "comment", "critic_comment", "delete", "emphasis", "escaped_text", "footnote_ref", "hard_break", "heading_ref", "highlight", "image", "inline_extension", "inline_footnote", "insert", "link", "literal_inline", "math", "mention", "raw_inline", "smart_punctuation", "soft_break", "span", "strike", "strong", "subscript", "substitution", "superscript", "symbol", "tag", "text", "underline"],
  "table_cell.children": ["abbreviation", "autolink", "caption_number", "citation_group", "code", "comment", "critic_comment", "delete", "emphasis", "escaped_text", "footnote_ref", "hard_break", "heading_ref", "highlight", "image", "inline_extension", "inline_footnote", "insert", "link", "literal_inline", "math", "mention", "raw_inline", "smart_punctuation", "soft_break", "span", "strike", "strong", "subscript", "substitution", "superscript", "symbol", "tag", "text", "underline"],
  "table_row.cells": ["table_cell"],
  "underline.children": ["abbreviation", "autolink", "caption_number", "citation_group", "code", "comment", "critic_comment", "delete", "emphasis", "escaped_text", "footnote_ref", "hard_break", "heading_ref", "highlight", "image", "inline_extension", "inline_footnote", "insert", "link", "literal_inline", "math", "mention", "raw_inline", "smart_punctuation", "soft_break", "span", "strike", "strong", "subscript", "substitution", "superscript", "symbol", "tag", "text", "underline"],
}
