// GENERATED by scripts/generate-wire-fields.mjs from resources/ast-schema.json.
// Do not edit: run `node scripts/generate-wire-fields.mjs` instead.
//
// PART 12 section 11 - a property the schema does not name is refused on
// ingest - needs the named set at runtime, and the schema is not shipped
// with the package.

/** Properties the schema names for each node type. */
export const WIRE_FIELDS: Readonly<Record<string, readonly string[]>> = {
  "abbreviation": ["abbr", "attrs", "expansion", "pos", "type"],
  "abbreviation_def": ["abbr", "attrs", "expansion", "pos", "type"],
  "admonition": ["attrs", "children", "kind", "label", "pos", "title", "type"],
  "autolink": ["attrs", "href", "pos", "text", "type"],
  "block_quote": ["attrs", "children", "pos", "type"],
  "caption_number": ["attrs", "n", "pos", "type"],
  "citation_group": ["attrs", "items", "mode", "pos", "raw", "type"],
  "code": ["attrs", "pos", "type", "value"],
  "code_block": ["attrs", "content", "header", "label", "lang", "pos", "type"],
  "comment": ["attrs", "block", "content", "pos", "type"],
  "critic_comment": ["attrs", "pos", "text", "type"],
  "definition_description": ["attrs", "children", "pos", "type"],
  "definition_list": ["attrs", "items", "pos", "type"],
  "definition_term": ["attrs", "children", "pos", "type"],
  "delete": ["attrs", "children", "pos", "type"],
  "div": ["attrs", "children", "label", "pos", "type"],
  "document": ["children", "srcByteLength", "type"],
  "emphasis": ["attrs", "children", "pos", "type"],
  "escaped_text": ["attrs", "pos", "type", "value"],
  "figure": ["attrs", "caption", "pos", "target", "type"],
  "footnote": ["attrs", "children", "label", "pos", "type"],
  "footnote_ref": ["attrs", "id", "number", "pos", "type"],
  "frontmatter": ["content", "format", "pos", "type"],
  "hard_break": ["attrs", "pos", "type"],
  "heading": ["attrs", "children", "level", "pos", "type"],
  "heading_ref": ["attrs", "href", "pos", "target", "type"],
  "highlight": ["attrs", "children", "pos", "type"],
  "image": ["alt", "attrs", "pos", "rawRef", "ref", "src", "title", "type"],
  "inline_extension": ["attrs", "content", "name", "pos", "type"],
  "inline_footnote": ["attrs", "inline", "number", "pos", "type"],
  "insert": ["attrs", "children", "pos", "type"],
  "line_block": ["attrs", "children", "pos", "type"],
  "link": ["attrs", "children", "href", "pos", "rawRef", "ref", "title", "type"],
  "link_reference_definition": ["attrs", "href", "label", "pos", "title", "type"],
  "list": ["attrs", "bareMarker", "bulletChar", "delim", "items", "olType", "ordered", "pos", "start", "tight", "type"],
  "list_item": ["attrs", "checked", "children", "pos", "type"],
  "literal_inline": ["attrs", "content", "pos", "type"],
  "math": ["attrs", "content", "display", "pos", "type"],
  "mention": ["attrs", "pos", "type", "user"],
  "paragraph": ["attrs", "children", "pos", "type"],
  "raw_block": ["attrs", "content", "format", "pos", "type"],
  "raw_inline": ["attrs", "content", "format", "pos", "type"],
  "smart_punctuation": ["attrs", "glyph", "kind", "pos", "type", "value"],
  "soft_break": ["attrs", "pos", "type"],
  "span": ["attrs", "children", "pos", "type"],
  "strike": ["attrs", "children", "pos", "type"],
  "strong": ["attrs", "boldItalic", "children", "pos", "type"],
  "subscript": ["attrs", "children", "pos", "type"],
  "substitution": ["attrs", "newText", "oldText", "pos", "type"],
  "superscript": ["attrs", "children", "pos", "type"],
  "symbol": ["attrs", "name", "pos", "type"],
  "table": ["attrs", "caption", "pos", "rows", "type"],
  "table_cell": ["align", "attrs", "children", "header", "pos", "span", "type"],
  "table_row": ["attrs", "cells", "pos", "type"],
  "tag": ["attrs", "name", "pos", "type"],
  "text": ["attrs", "pos", "type", "value"],
  "thematic_break": ["attrs", "pos", "type"],
  "underline": ["attrs", "children", "pos", "type"],
}

/** Properties the schema names for the objects that hang off a node. */
export const WIRE_HELPER_FIELDS: Readonly<Record<string, readonly string[]>> = {
  "attrs": ["classes", "id", "keyValues", "order"],
  "pos": ["endColumn", "endLine", "endOffset", "startColumn", "startLine", "startOffset"],
}

/**
 * Field names that hold NODES, so section 12(c)'s unknown-type check knows
 * where a node can be. A union across types: `content` holds nodes on
 * `inline_extension` and a string on `code_block`, and descending a name into
 * a string finds nothing, so the union is safe in both directions.
 *
 * `keyValues` is absent, and that is the point: its values are strings, and an
 * attribute may legally be named `type`, so `{type=widget}` puts an object
 * shaped {"type":"widget"} in the tree.
 */
export const NODE_FIELDS: readonly string[] = [
  "caption",
  "cells",
  "children",
  "content",
  "inline",
  "items",
  "locator",
  "prefix",
  "rows",
  "suffix",
  "target",
  "title",
]

/**
 * What the schema puts at each node position, keyed `<owning type>.<field>`,
 * so section 12(c)'s string-`type` requirement lands where a NODE belongs and
 * nowhere else.
 *
 * - `"nodes"` - an array of nodes; each ELEMENT carries a string `type`. About
 *   the elements, not the container: a non-array sitting where the array
 *   belongs is the unruled wrong-TYPE class, not this clause's business.
 * - `"node"` - a single node, e.g. `figure.target`; the object itself carries
 *   one.
 * - `"records"` - an array of plain records the schema gives no `type` at all.
 *   Only `citation_group.items` today: a citation item is
 *   `{key, suppressAuthor, prefix?, locator?, suffix?}`.
 *
 * The owning type is part of the key because one field name means different
 * things in different places: `items` holds nodes on `list` and plain records
 * on `citation_group`.
 */
export const NODE_POSITION_KIND: Readonly<Record<string, 'nodes' | 'node' | 'records'>> = {
  "admonition.children": "nodes",
  "admonition.title": "nodes",
  "block_quote.children": "nodes",
  "citation_group.items": "records",
  "definition_description.children": "nodes",
  "definition_list.items": "nodes",
  "definition_term.children": "nodes",
  "delete.children": "nodes",
  "div.children": "nodes",
  "document.children": "nodes",
  "emphasis.children": "nodes",
  "figure.caption": "nodes",
  "figure.target": "node",
  "footnote.children": "nodes",
  "heading.children": "nodes",
  "highlight.children": "nodes",
  "inline_extension.content": "nodes",
  "inline_footnote.inline": "nodes",
  "insert.children": "nodes",
  "line_block.children": "nodes",
  "link.children": "nodes",
  "list.items": "nodes",
  "list_item.children": "nodes",
  "paragraph.children": "nodes",
  "span.children": "nodes",
  "strike.children": "nodes",
  "strong.children": "nodes",
  "subscript.children": "nodes",
  "superscript.children": "nodes",
  "table.caption": "nodes",
  "table.rows": "nodes",
  "table_cell.children": "nodes",
  "table_row.cells": "nodes",
  "underline.children": "nodes",
}
